### ISSUE TITLE
Clean bower.json

### ISSUE THREAD

**Issue by lxbrito** [PolymerElements/platinum-elements#4]
The 'main' entry is referring to a non-existent file and should be removed.

"main": "service-worker-elements.html",

This is breaking Rails assets compilation.

**Comment by addyosmani** [comment]
Thanks for bringing this to my attention. Dropped in https://github.com/PolymerElements/platinum-elements/commit/9031a782fa9c0046f481602e2370f623034bf53b. We originally intended on having a meta-import for all the platinum-* files, but never got around to adding it.

**Comment by beaufortfrancois** [comment]
Can we close this one @addyosmani?
