### ISSUE TITLE
Prepare next release

### ISSUE THREAD

**Issue by addyosmani** [PolymerElements/platinum-elements#9]
- [ ] Test platinum-bluetooth with the element catalog locally to make sure docs/content render as expected
- [ ] Attempt to pull in latest master with the new platinum-bluetooth element into projects like PSK or those using it. Ensure there's no breakage.
- [ ] Tag next release.

**Comment by jeffposnick** [comment]
PSK pulls in everything properly with `"platinum-elements": "PolymerElements/platinum-elements#master"` in a local copy of its `bower.json`.

How does one test the element catalog? #AskingForAFriend #OkayBeenMeaningToAsk

**Comment by beaufortfrancois** [comment]
For info, I've checked out https://github.com/Polymer/polymer-element-catalog and installed bower dependencies. Then I simply run
```bash
bower install --save PolymerElements/platinum-elements#master
npm run build
npm run serve
```
And check out http://localhost:3000/browse?package=platinum-elements

**Comment by beaufortfrancois** [comment]
![screenshot 2015-08-19 at 12 22 48 pm](https://cloud.githubusercontent.com/assets/634478/9353992/0e202b5c-466d-11e5-9edd-725712f32e45.png)

**Comment by addyosmani** [comment]
@beaufortfrancois's outline for checking it out is correct :) atm it looks like this is all good to go for a tag.

**Comment by beaufortfrancois** [comment]
:yellow_heart:

**Comment by jeffposnick** [comment]
I don't believe the tagging for `<platinum-bluetooth>` happened yet, right? Once https://github.com/PolymerElements/platinum-elements/pull/10 is merged we can get a new release tagged that includes `<platinum-https-redirect>` as well.

**Comment by wibblymat** [comment]
Looks like this was all done with tag v1.2.0, closing.
